<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://tempuri.org/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Service1" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="getGeocode">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="address" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="getGeocodeResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="getGeocodeResult" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="getAddress">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="latitude" type="xs:double" />
            <xs:element minOccurs="0" name="longitude" type="xs:double" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="getAddressResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="getAddressResult" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="findRoute">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="begin" nillable="true" type="xs:string" />
            <xs:element minOccurs="0" name="end" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="findRouteResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="findRouteResult" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="getMap">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="begin" nillable="true" type="xs:string" />
            <xs:element minOccurs="0" name="end" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="getMapResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="getMapResult" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
    <xs:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="anyType" nillable="true" type="xs:anyType" />
      <xs:element name="anyURI" nillable="true" type="xs:anyURI" />
      <xs:element name="base64Binary" nillable="true" type="xs:base64Binary" />
      <xs:element name="boolean" nillable="true" type="xs:boolean" />
      <xs:element name="byte" nillable="true" type="xs:byte" />
      <xs:element name="dateTime" nillable="true" type="xs:dateTime" />
      <xs:element name="decimal" nillable="true" type="xs:decimal" />
      <xs:element name="double" nillable="true" type="xs:double" />
      <xs:element name="float" nillable="true" type="xs:float" />
      <xs:element name="int" nillable="true" type="xs:int" />
      <xs:element name="long" nillable="true" type="xs:long" />
      <xs:element name="QName" nillable="true" type="xs:QName" />
      <xs:element name="short" nillable="true" type="xs:short" />
      <xs:element name="string" nillable="true" type="xs:string" />
      <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte" />
      <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt" />
      <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong" />
      <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort" />
      <xs:element name="char" nillable="true" type="tns:char" />
      <xs:simpleType name="char">
        <xs:restriction base="xs:int" />
      </xs:simpleType>
      <xs:element name="duration" nillable="true" type="tns:duration" />
      <xs:simpleType name="duration">
        <xs:restriction base="xs:duration">
          <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?" />
          <xs:minInclusive value="-P10675199DT2H48M5.4775808S" />
          <xs:maxInclusive value="P10675199DT2H48M5.4775807S" />
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="guid" nillable="true" type="tns:guid" />
      <xs:simpleType name="guid">
        <xs:restriction base="xs:string">
          <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}" />
        </xs:restriction>
      </xs:simpleType>
      <xs:attribute name="FactoryType" type="xs:QName" />
      <xs:attribute name="Id" type="xs:ID" />
      <xs:attribute name="Ref" type="xs:IDREF" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="IService1_getGeocode_InputMessage">
    <wsdl:part name="parameters" element="tns:getGeocode" />
  </wsdl:message>
  <wsdl:message name="IService1_getGeocode_OutputMessage">
    <wsdl:part name="parameters" element="tns:getGeocodeResponse" />
  </wsdl:message>
  <wsdl:message name="IService1_getAddress_InputMessage">
    <wsdl:part name="parameters" element="tns:getAddress" />
  </wsdl:message>
  <wsdl:message name="IService1_getAddress_OutputMessage">
    <wsdl:part name="parameters" element="tns:getAddressResponse" />
  </wsdl:message>
  <wsdl:message name="IService1_findRoute_InputMessage">
    <wsdl:part name="parameters" element="tns:findRoute" />
  </wsdl:message>
  <wsdl:message name="IService1_findRoute_OutputMessage">
    <wsdl:part name="parameters" element="tns:findRouteResponse" />
  </wsdl:message>
  <wsdl:message name="IService1_getMap_InputMessage">
    <wsdl:part name="parameters" element="tns:getMap" />
  </wsdl:message>
  <wsdl:message name="IService1_getMap_OutputMessage">
    <wsdl:part name="parameters" element="tns:getMapResponse" />
  </wsdl:message>
  <wsdl:portType name="IService1">
    <wsdl:operation name="getGeocode">
      <wsdl:input wsaw:Action="http://tempuri.org/IService1/getGeocode" message="tns:IService1_getGeocode_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IService1/getGeocodeResponse" message="tns:IService1_getGeocode_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="getAddress">
      <wsdl:input wsaw:Action="http://tempuri.org/IService1/getAddress" message="tns:IService1_getAddress_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IService1/getAddressResponse" message="tns:IService1_getAddress_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="findRoute">
      <wsdl:input wsaw:Action="http://tempuri.org/IService1/findRoute" message="tns:IService1_findRoute_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IService1/findRouteResponse" message="tns:IService1_findRoute_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="getMap">
      <wsdl:input wsaw:Action="http://tempuri.org/IService1/getMap" message="tns:IService1_getMap_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IService1/getMapResponse" message="tns:IService1_getMap_OutputMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_IService1" type="tns:IService1">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="getGeocode">
      <soap:operation soapAction="http://tempuri.org/IService1/getGeocode" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getAddress">
      <soap:operation soapAction="http://tempuri.org/IService1/getAddress" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="findRoute">
      <soap:operation soapAction="http://tempuri.org/IService1/findRoute" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getMap">
      <soap:operation soapAction="http://tempuri.org/IService1/getMap" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Service1">
    <wsdl:port name="BasicHttpBinding_IService1" binding="tns:BasicHttpBinding_IService1">
      <soap:address location="http://localhost:63884/Service1.svc" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>